# Generated by Django 5.2.8 on 2025-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LOAN', 'On Loan'), ('MAINTENANCE', 'Maintenance'), ('PENDING', 'Pending Approval')], default='AVAILABLE', max_length=20),
        ),
    ]
